// <auto-generated />
using Gis.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gis.DAL.Migrations
{
    [DbContext(typeof(GisDbContext))]
    [Migration("20250505202152_InitialDatabaseState")]
    partial class InitialDatabaseState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gis.DAL.Models.Market", b =>
                {
                    b.Property<int>("Objectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OBJECTID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Objectid"));

                    b.Property<string>("Address")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("address");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("numeric(38, 8)")
                        .HasColumnName("lat");

                    b.Property<decimal?>("Lon")
                        .HasColumnType("numeric(38, 8)")
                        .HasColumnName("lon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("Objectid")
                        .HasName("PK__MARKETS__F4B70D851C07A19D");

                    b.ToTable("MARKETS");
                });

            modelBuilder.Entity("Gis.DAL.Models.Mosque", b =>
                {
                    b.Property<int>("Objectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OBJECTID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Objectid"));

                    b.Property<string>("Address")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("address");

                    b.Property<decimal>("Lat")
                        .HasColumnType("numeric(38, 8)")
                        .HasColumnName("lat");

                    b.Property<decimal>("Lon")
                        .HasColumnType("numeric(38, 8)")
                        .HasColumnName("lon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("Objectid")
                        .HasName("PK__MOSQUE__F4B70D8564EDCE8D");

                    b.ToTable("MOSQUE");
                });

            modelBuilder.Entity("Gis.DAL.Models.Pharmacy", b =>
                {
                    b.Property<int>("Objectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OBJECTID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Objectid"));

                    b.Property<string>("Address")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("address");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("numeric(38, 8)")
                        .HasColumnName("lat");

                    b.Property<decimal?>("Lon")
                        .HasColumnType("numeric(38, 8)")
                        .HasColumnName("lon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("Objectid")
                        .HasName("PK__PHARMACI__F4B70D85F6C427D8");

                    b.ToTable("PHARMACIES");
                });

            modelBuilder.Entity("Gis.DAL.Models.Restaurant", b =>
                {
                    b.Property<int>("Objectid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OBJECTID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Objectid"));

                    b.Property<string>("Address")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("address");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("numeric(38, 8)")
                        .HasColumnName("lat");

                    b.Property<decimal?>("Lon")
                        .HasColumnType("numeric(38, 8)")
                        .HasColumnName("lon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("Objectid")
                        .HasName("PK__RESTAURA__F4B70D85EC419432");

                    b.ToTable("RESTAURANT");
                });
#pragma warning restore 612, 618
        }
    }
}
