// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Gis.DAL.Models;

[Table("RESTAURANT")]
public partial class Restaurant: BaseEntity
{
  
    [StringLength(254)]
    public string? Name { get; set; }

    [Column("address")]
    [StringLength(254)]
    public string? Address { get; set; }

    [Column("lat", TypeName = "numeric(38, 8)")]
    public decimal? Lat { get; set; }

    [Column("lon", TypeName = "numeric(38, 8)")]
    public decimal? Lon { get; set; }
}