// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Gis.DAL.Data;
using Gis.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Gis.DAL.Data.Configurations
{
    public partial class MosqueConfiguration : IEntityTypeConfiguration<Mosque>
    {
        public void Configure(EntityTypeBuilder<Mosque> entity)
        {
            entity.HasKey(e => e.Objectid).HasName("PK__MOSQUE__F4B70D8564EDCE8D");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Mosque> entity);
    }
}
