// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Gis.DAL.Data;
using Gis.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Gis.DAL.Data.Configurations
{
    public partial class PharmacyConfiguration : IEntityTypeConfiguration<Pharmacy>
    {
        public void Configure(EntityTypeBuilder<Pharmacy> entity)
        {
            entity.HasKey(e => e.Objectid).HasName("PK__PHARMACI__F4B70D85F6C427D8");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Pharmacy> entity);
    }
}
