// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Gis.DAL.Data;
using Gis.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Gis.DAL.Data.Configurations
{
    public partial class RestaurantConfiguration : IEntityTypeConfiguration<Restaurant>
    {
        public void Configure(EntityTypeBuilder<Restaurant> entity)
        {
            entity.HasKey(e => e.Objectid).HasName("PK__RESTAURA__F4B70D85EC419432");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Restaurant> entity);
    }
}
