// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Gis.DAL.Data;
using Gis.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Gis.DAL.Data.Configurations
{
    public partial class StudentHousingConfiguration : IEntityTypeConfiguration<StudentHousing>
    {
        public void Configure(EntityTypeBuilder<StudentHousing> entity)
        {
            entity.HasKey(e => e.Objectid).HasName("PK__STUDENT___F4B70D85049E434C");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StudentHousing> entity);
    }
}
